In [1]:
# Library imports.
import pandas as pd

In [7]:
# Loading SPSS .SAV files into a Pandas dataframe.
# https://pandas.pydata.org/docs/reference/api/pandas.read_spss.html
pf_1 = pd.read_spss("../data/raw/anchor/anchor1.sav")
pf_2 = pd.read_spss("../data/raw/anchor/anchor2.sav")
pf_9 = pd.read_spss("../data/raw/anchor/anchor9.sav")

In [25]:
biopart = pd.read_spss("../data/raw/bio/biopart.sav")

In [40]:
biopart_mod = biopart[["id", "pid", "partindex", "cohort", "sex", "sexp", "homosex_p", "dob", "dobp", "relbeg", "relend", "cohbeg", "cohend", "marbeg", "marend", "marcer"]]

In [41]:
biopart_mod[["id", "pid", "dob", "dobp", "relbeg", "relend", "cohbeg", "cohend", "marbeg", "marend", "marcer"]]

,id,pid,partindex,cohort,sex,sexp,homosex_p,dob,dobp,relbeg,relend,cohbeg,cohend,marbeg,marend,marcer
0,111000.0,NaN,1st partner,3 1971-1973,2 Female,1 Male,0 Hetereosexual union,855.0,NaN,1058.0,1089.0,1058.0,1089.0,1085.0,1089.0,1 Only a civil ceremony
1,111000.0,NaN,2nd partner,3 1971-1973,2 Female,1 Male,0 Hetereosexual union,855.0,NaN,1094.0,1141.0,NaN,NaN,NaN,NaN,NaN
2,111000.0,NaN,3rd partner,3 1971-1973,2 Female,1 Male,0 Hetereosexual union,855.0,NaN,1209.0,1230.0,NaN,NaN,NaN,NaN,NaN
3,111000.0,NaN,4th partner,3 1971-1973,2 Female,1 Male,0 Hetereosexual union,855.0,NaN,1274.0,1302.0,NaN,NaN,NaN,NaN,NaN
4,111000.0,111102.0,5th partner,3 1971-1973,2 Female,1 Male,0 Hetereosexual union,855.0,824.0,1317.0,1342.0,1339.0,1342.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37545,953978000.0,953978101.0,1st partner,4 2001-2003,1 Male,2 Female,0 Hetereosexual union,1234.0,1232.0,1406.0,NaN,NaN,NaN,NaN,NaN,NaN
37546,953997000.0,NaN,1st partner,1 1991-1993,1 Male,2 Female,0 Hetereosexual union,1112.0,NaN,1440.0,1443.0,NaN,NaN,NaN,NaN,NaN
37547,953997000.0,NaN,2nd partner,1 1991-1993,1 Male,2 Female,0 Hetereosexual union,1112.0,NaN,1447.0,1449.0,NaN,NaN,NaN,NaN,NaN
37548,953998000.0,NaN,1st partner,1 1991-1993,2 Female,1 Male,0 Hetereosexual union,1101.0,NaN,1321.0,1361.0,NaN,NaN,NaN,NaN,NaN
37549,953998000.0,NaN,2nd partner,1 1991-1993,2 Female,1 Male,0 Hetereosexual union,1101.0,NaN,1397.0,1415.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Check first lines of dataset.
pf_1.head()

,id,demodiff,wave,sample,pid,parentidk1,parentidk2,parentidk3,parentidk4,parentidk5,...,int4i5,int4i5o,int5,int6,int7,int8,int9,int9o,int10i1,int10i2
0,111000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,NaN,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,3 No,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,1 Respondent doesn't have a partner or refused...,7 No partner,NaN,1.0,0.0
1,174000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,NaN,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,1 Respondent doesn't have a partner or refused...,7 No partner,NaN,2.0,0.0
2,309000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,309101.0,309101.0,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,3 No,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,3 Handed out before CASI part,1 Questionnaire was handed out during intervie...,NaN,2.0,0.0
3,423000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,NaN,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,3 No,1 Respondent may be interviewed again by TNS I...,4.0,1 Respondent doesn't have a partner or refused...,7 No partner,NaN,2.0,0.0
4,828000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,NaN,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,1 Respondent doesn't have a partner or refused...,7 No partner,NaN,3.0,0.0

In [8]:
# Filter out respondents without partners.
pf_1 = pf_1.dropna(subset="pid")
pf_1

,id,demodiff,wave,sample,pid,parentidk1,parentidk2,parentidk3,parentidk4,parentidk5,...,int4i5,int4i5o,int5,int6,int7,int8,int9,int9o,int10i1,int10i2
2,309000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,309101.0,309101.0,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,3 No,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,3 Handed out before CASI part,1 Questionnaire was handed out during intervie...,NaN,2.0,0.0
5,907000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,907101.0,907101.0,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,3 Handed out before CASI part,"2 Questionnaire was handed out, pick-up was ar...",NaN,1.0,0.0
7,1028000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,1028101.0,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,3 Handed out before CASI part,"3 Questionnaire was handed out, agreement was ...",NaN,1.0,2.0
12,1299000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,1299101.0,1299101.0,1299101.0,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,4 Handed out at the end,"2 Questionnaire was handed out, pick-up was ar...",NaN,4.0,0.0
13,1300000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,1300101.0,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,4 Handed out at the end,"2 Questionnaire was handed out, pick-up was ar...",NaN,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12393,749211000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,749211101.0,749211101.0,749211101.0,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,4.0,2 Questionnaire will be sent by mail,5 Sending and returning by mail was arranged,NaN,3.0,0.0
12394,749410000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,749410101.0,749410101.0,749410101.0,NaN,NaN,NaN,...,0 Not mentioned,NaN,3 No,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,1 Respondent doesn't have a partner or refused...,4 Interview of partner refused,NaN,4.0,0.0
12395,749432000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,749432101.0,749432101.0,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,4.0,2 Questionnaire will be sent by mail,5 Sending and returning by mail was arranged,NaN,3.0,0.0
12396,749472000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,749472101.0,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,5 Very much willing to be interviewed again,4 Handed out at the end,"2 Questionnaire was handed out, pick-up was ar...",NaN,3.0,0.0
12400,749725000.0,0 non-demodiff,1 2008/09,1 pairfam base sample,749725101.0,NaN,NaN,NaN,NaN,NaN,...,0 Not mentioned,NaN,NaN,1 Respondent may be interviewed again by TNS I...,2.0,2 Questionnaire will be sent by mail,5 Sending and returning by mail was arranged,NaN,5.0,2.0

In [8]:
# All variables names.
list(pf_2)

['id',
 'demodiff',
 'wave',
 'sample',
 'pid',
 'mid',
 'fid',
 'smid',
 'sfid',
 'cid1',
 'cid2',
 'cid3',
 'cid4',
 'cid5',
 'cid6',
 'cid7',
 'cid8',
 'cid9',
 'cid10',
 'parentidk1',
 'parentidk2',
 'parentidk3',
 'parentidk4',
 'parentidk5',
 'parentidk6',
 'parentidk7',
 'parentidk8',
 'parentidk9',
 'parentidk10',
 'parentidk11',
 'parentidk12',
 'parentidk13',
 'parentidk14',
 'parentidk15',
 'sex_gen',
 'psex_gen',
 'k1sex_gen',
 'k2sex_gen',
 'k3sex_gen',
 'k4sex_gen',
 'k5sex_gen',
 'k6sex_gen',
 'k7sex_gen',
 'k8sex_gen',
 'k9sex_gen',
 'k10sex_gen',
 'doby_gen',
 'dobm_gen',
 'pdoby_gen',
 'pdobm_gen',
 'mdoby_gen',
 'mdobm_gen',
 'fdoby_gen',
 'fdobm_gen',
 'smdoby_gen',
 'smdobm_gen',
 'sfdoby_gen',
 'sfdobm_gen',
 'k1doby_gen',
 'k2doby_gen',
 'k3doby_gen',
 'k4doby_gen',
 'k5doby_gen',
 'k6doby_gen',
 'k7doby_gen',
 'k8doby_gen',
 'k9doby_gen',
 'k10doby_gen',
 'k1dobm_gen',
 'k2dobm_gen',
 'k3dobm_gen',
 'k4dobm_gen',
 'k5dobm_gen',
 'k6dobm_gen',
 'k7dobm_gen',
 'k8dobm_gen',
 'k9dobm_gen',
 'k10dobm_gen',
 'age',
 'page',
 'mage',
 'fage',
 'smage',
 'sfage',
 'k1age',
 'k2age',
 'k3age',
 'k4age',
 'k5age',
 'k6age',
 'k7age',
 'k8age',
 'k9age',
 'k10age',
 'ykage',
 'ykid',
 'ykagecapi',
 'cohort',
 'cob',
 'pcob',
 'mcob',
 'fcob',
 'nat1',
 'nat2',
 'pnat1',
 'pnat2',
 'mnat1',
 'mnat2',
 'fnat1',
 'fnat2',
 'ethni',
 'migstatus',
 'relstat',
 'marstat',
 'pmarstat',
 'np',
 'ncoh',
 'nmar',
 'meetdur',
 'reldur',
 'cohabdur',
 'mardur',
 'homosex',
 'homosex_new',
 'infertile',
 'pregnant',
 'nkids',
 'nkidsbio',
 'nkidsp',
 'nkidsalv',
 'nkidsbioalv',
 'nkidspalv',
 'nkidsliv',
 'nkidsbioliv',
 'nkidspliv',
 'pnkidsbioalv',
 'k1type',
 'k2type',
 'k3type',
 'k4type',
 'k5type',
 'k6type',
 'k7type',
 'k8type',
 'k9type',
 'k10type',
 'res2nd',
 'hhsizemrd',
 'mmrd',
 'fmrd',
 'childmrd',
 'othmrd',
 'hhcomp',
 'enrol',
 'penrol',
 'school',
 'pschool',
 'mschool',
 'fschool',
 'vocat',
 'pvocat',
 'mvocat',
 'fvocat',
 'isced',
 'pisced',
 'misced',
 'fisced',
 'isced2',
 'pisced2',
 'casmin',
 'pcasmin',
 'mcasmin',
 'fcasmin',
 'yeduc',
 'pyeduc',
 'myeduc',
 'fyeduc',
 'kldb2010',
 'kldb1992',
 'isco08',
 'isco88',
 'egp',
 'isei',
 'siops',
 'mps',
 'incnet',
 'hhincnet',
 'hhincgcee',
 'hhincoecd',
 'npu14mr',
 'npo14mr',
 'cpi',
 'casprim',
 'cassec',
 'pcasprim',
 'pcassec',
 'lfs',
 'plfs',
 'east',
 'bula',
 'gkpol',
 'bik',
 'intcont',
 'intsex',
 'intage',
 'intid',
 'intdur',
 'intd',
 'intm',
 'inty',
 'wavedist',
 'dweight',
 'd1weight',
 'd2weight',
 'd3weight',
 'cdweight',
 'cd1weight',
 'cd2weight',
 'cd3weight',
 'flag1',
 'flag2',
 'flag3',
 'flag4',
 'flag5',
 'flag6',
 'flag7',
 'flag8',
 'flag9',
 'flag10',
 'flag11',
 'flag12',
 'flag13',
 'flag14',
 'flag15',
 'flag16',
 'flag17',
 'flag18',
 'flag20',
 'flag21',
 'flag22',
 'flag23',
 'flag24',
 'flag25',
 'flag26',
 'flag27',
 'flag_cas',
 'pflag_cas',
 'flag_ehc',
 'flag_frt6',
 'flag_igb',
 'flag_isco08_kldb2010',
 'tag_sex',
 'tag_dob',
 'tag_identk1',
 'tag_identk2',
 'tag_identk3',
 'tag_identk4',
 'tag_identk5',
 'tag_identk6',
 'tag_identk7',
 'tag_identk8',
 'tag_identk9',
 'tag_identk10',
 'tag_sexk1',
 'tag_sexk2',
 'tag_sexk3',
 'tag_sexk4',
 'tag_sexk5',
 'tag_sexk6',
 'tag_sexk7',
 'tag_sexk8',
 'tag_sexk9',
 'tag_sexk10',
 'tag_dobk1',
 'tag_dobk2',
 'tag_dobk3',
 'tag_dobk4',
 'tag_dobk5',
 'tag_dobk6',
 'tag_dobk7',
 'tag_dobk8',
 'tag_dobk9',
 'tag_dobk10',
 'tag_biok1',
 'tag_biok2',
 'tag_biok3',
 'tag_biok4',
 'tag_biok5',
 'tag_biok6',
 'tag_biok7',
 'tag_biok8',
 'tag_biok9',
 'tag_biok10',
 'tag_biokp1',
 'tag_biokp2',
 'tag_biokp3',
 'tag_biokp4',
 'tag_biokp5',
 'tag_biokp6',
 'tag_biokp7',
 'tag_biokp8',
 'tag_biokp9',
 'tag_biokp10',
 'tag_identp',
 'tag_dobp',
 'tag_sexp',
 'hp',
 'hp0',
 'hae',
 'lmhh1',
 'lmhh2',
 'lvhh1',
 'lvhh2',
 'amhh1',
 'amhh2',
 'avhh1',
 'avhh2',
 'smhh1',
 'smhh2',
 'svhh1',
 'svhh2',
 'hm1',
 'hm2',
 'hv1',
 'hv2',
 'he1',
 'he2',
 'he3',
 'hsv1',
 'hsv2',
 'hsm1',
 'hsm2',
 'hnk',
 'capikid',
 'netd1',
 'netd2',
 'netd3',
 'netd4',
 'netd5',
 'netd6',
 'netd7',
 'netd8',
 'netp1n',
 'netp2n',
 'netp3n',
 'netp4n',
 'netp5n',
 'netp6n',
 'netp7n',
 'netp8n',
 'netp9n',
 'netp10n',
 'netp11n',
 'netp12n',
 'netp13n',
 'netp14n',
 'netp15n',
 'netp16n',
 'netp17n',
 'netp18n',
 'netp19n',
 'netp20n',
 'netp21n',
 'netp22n',
 'netp23n',
 'netp24n',
 'netp25n',
 'netp26n',
 'netp27n',
 'netp28n',
 'netp29n',
 'netp30n',
 'd1',
 'd2',
 'd3',
 'd4',
 'd5',
 'd6',
 'd7',
 'd8',
 'd9',
 'd10',
 'd11',
 'd12',
 'd13',
 'd14',
 'd15',
 'd16',
 'd17',
 'd18',
 'd19',
 'd20',
 'd21',
 'd22',
 'd23',
 'd29',
 'd30',
 'd31',
 'd32',
 'd33',
 'd34',
 'd35',
 'd36',
 'd37',
 'd38',
 'd44',
 'd45',
 'd46',
 'd47',
 'd48',
 'd49',
 'd50',
 'd51',
 'd52',
 'd53',
 'd342',
 'd343',
 'd344',
 'd345',
 'd346',
 'd347',
 'd348',
 'd349',
 'd350',
 'd351',
 'd59',
 'd60',
 'd61',
 'd62',
 'd63',
 'd64',
 'd65',
 'd66',
 'd67',
 'd68',
 'd69',
 'd70',
 'd71',
 'd72',
 'd73',
 'd74',
 'd75',
 'd76',
 'd77',
 'd78',
 'd79',
 'd80',
 'd81',
 'd82',
 'd83',
 'd84',
 'd85',
 'd86',
 'd87',
 'd88',
 'd89',
 'd90',
 'd91',
 'd92',
 'd93',
 'd94',
 'd95',
 'd96',
 'd97',
 'd98',
 'd99',
 'd100',
 'd101',
 'd102',
 'd103',
 'd104',
 'd105',
 'd106',
 'd107',
 'd108',
 'd109',
 'd110',
 'd111',
 'd112',
 'd113',
 'd119',
 'd120',
 'd121',
 'd122',
 'd123',
 'd124',
 'd125',
 'd327',
 'd328',
 'd329',
 'd330',
 'd331',
 'd332',
 'd333',
 'd334',
 'd335',
 'd336',
 'd134',
 'd135',
 'd136',
 'd137',
 'd138',
 'd139',
 'd154',
 'd155',
 'd156',
 'd157',
 'd158',
 'd159',
 'd164',
 'd165',
 'd166',
 'd167',
 'd174',
 'd175',
 'd176',
 'd177',
 'd178',
 'd179',
 'd180',
 'd181',
 'd182',
 'd183',
 'd184',
 'd185',
 'd186',
 'd187',
 'd188',
 'd189',
 'd190',
 'd191',
 'd192',
 'd193',
 'd194',
 'd196',
 'd197',
 'd198',
 'd199',
 'd200',
 'd201',
 'd202',
 'd203',
 'd204',
 'd205',
 'd206',
 'd207',
 'd208',
 'd209',
 'd210',
 'd211',
 'd212',
 'd213',
 'd214',
 'd357',
 'd358',
 'd359',
 'd360',
 'd361',
 'd362',
 'd363',
 'd364',
 'd365',
 'd366',
 'd367',
 'd368',
 'd369',
 'd370',
 'd371',
 'd372',
 'd373',
 'd374',
 'd375',
 'd216',
 'd217',
 'd218',
 'd219',
 'd220',
 'd221',
 'd222',
 'd223',
 'd224',
 'd225',
 'd226',
 'd238',
 'd239',
 'd240',
 'd241',
 'd242',
 'd243',
 'd244',
 'd245',
 'd246',
 'd377',
 'd378',
 'd379',
 'd380',
 'd381',
 'd382',
 'd383',
 'd384',
 'd385',
 'd258',
 'd259',
 'd260',
 'd261',
 'd262',
 'd263',
 'd264',
 'd265',
 'd266',
 'd267',
 'd268',
 'd269',
 'd270',
 'd271',
 'd272',
 'd273',
 'd274',
 'd275',
 'd276',
 'd277',
 'd278',
 'd279',
 'd280',
 'd281',
 'd282',
 'd283',
 'd284',
 'd285',
 'd301',
 'd317',
 'd397',
 'd398',
 'd318',
 'd319',
 'd320',
 'd321',
 'd322',
 'd323',
 'd324',
 'd325',
 'd326',
 'original_sex',
 'original_dobm',
 'original_doby',
 'dobd',
 'val2i1',
 'val2i2',
 'val2i3',
 'val2i4',
 'val2i5',
 'val2i6',
 'sat1i1',
 'sat1i2',
 'sat1i3',
 'sat1i4',
 'srs1i1',
 'srs1i2',
 'srs1i3',
 'srs1i4',
 'srs1i5',
 'ehcid',
 'ehc1p1n',
 'ehc1p1g',
 'ehc2p1m1',
 'ehc2p1m2',
 'ehc2p1m3',
 'ehc2p1m4',
 'ehc2p1m5',
 'ehc2p1m6',
 'ehc2p1m7',
 'ehc2p1m8',
 'ehc2p1m9',
 'ehc2p1m10',
 'ehc2p1m11',
 'ehc2p1m12',
 'ehc2p1m13',
 'ehc2p1m14',
 'ehc2p1m15',
 'ehc2p1m16',
 'ehc2p1m17',
 'ehc2p1m18',
 'ehc2p1',
 'ehc3p1m1',
 'ehc3p1m2',
 'ehc3p1m3',
 'ehc3p1m4',
 'ehc3p1m5',
 'ehc3p1m6',
 'ehc3p1m7',
 'ehc3p1m8',
 'ehc3p1m9',
 'ehc3p1m10',
 'ehc3p1m11',
 'ehc3p1m12',
 'ehc3p1m13',
 'ehc3p1m14',
 'ehc3p1m15',
 'ehc3p1m16',
 'ehc3p1m17',
 'ehc3p1m18',
 'ehc3p1',
 'ehc4p1m1',
 'ehc4p1m2',
 'ehc4p1m3',
 'ehc4p1m4',
 'ehc4p1m5',
 'ehc4p1m6',
 'ehc4p1m7',
 'ehc4p1m8',
 'ehc4p1m9',
 'ehc4p1m10',
 'ehc4p1m11',
 'ehc4p1m12',
 'ehc4p1m13',
 'ehc4p1m14',
 'ehc4p1m15',
 'ehc4p1m16',
 'ehc4p1m17',
 'ehc4p1m18',
 'ehc4p1',
 'ehc5p1',
 'ehc6p1',
 'ehc6p1m',
 'ehc6p1y',
 'ehc1p2n',
 'ehc1p2g',
 'ehc2p2m1',
 'ehc2p2m2',
 'ehc2p2m3',
 'ehc2p2m4',
 'ehc2p2m5',
 'ehc2p2m6',
 'ehc2p2m7',
 'ehc2p2m8',
 'ehc2p2m9',
 'ehc2p2m10',
 'ehc2p2m11',
 'ehc2p2m12',
 'ehc2p2m13',
 'ehc2p2m14',
 'ehc2p2m15',
 'ehc2p2m16',
 'ehc2p2m17',
 'ehc2p2m18',
 'ehc2p2',
 'ehc3p2m1',
 'ehc3p2m2',
 'ehc3p2m3',
 'ehc3p2m4',
 'ehc3p2m5',
 'ehc3p2m6',
 'ehc3p2m7',
 'ehc3p2m8',
 'ehc3p2m9',
 'ehc3p2m10',
 'ehc3p2m11',
 'ehc3p2m12',
 'ehc3p2m13',
 'ehc3p2m14',
 'ehc3p2m15',
 'ehc3p2m16',
 'ehc3p2m17',
 'ehc3p2m18',
 'ehc3p2',
 'ehc4p2m1',
 'ehc4p2m2',
 'ehc4p2m3',
 'ehc4p2m4',
 'ehc4p2m5',
 'ehc4p2m6',
 'ehc4p2m7',
 'ehc4p2m8',
 'ehc4p2m9',
 'ehc4p2m10',
 'ehc4p2m11',
 'ehc4p2m12',
 'ehc4p2m13',
 'ehc4p2m14',
 'ehc4p2m15',
 'ehc4p2m16',
 'ehc4p2m17',
 'ehc4p2m18',
 'ehc4p2',
 'ehc5p2',
 'ehc6p2',
 'ehc6p2m',
 'ehc6p2y',
 'ehc1p3n',
 'ehc1p3g',
 'ehc2p3m1',
 'ehc2p3m2',
 'ehc2p3m3',
 'ehc2p3m4',
 'ehc2p3m5',
 'ehc2p3m6',
 'ehc2p3m7',
 'ehc2p3m8',
 'ehc2p3m9',
 'ehc2p3m10',
 'ehc2p3m11',
 'ehc2p3m12',
 'ehc2p3m13',
 'ehc2p3m14',
 'ehc2p3m15',
 'ehc2p3m16',
 'ehc2p3m17',
 'ehc2p3m18',
 'ehc2p3',
 'ehc3p3m1',
 'ehc3p3m2',
 'ehc3p3m3',
 'ehc3p3m4',
 'ehc3p3m5',
 'ehc3p3m6',
 'ehc3p3m7',
 'ehc3p3m8',
 'ehc3p3m9',
 'ehc3p3m10',
 'ehc3p3m11',
 'ehc3p3m12',
 'ehc3p3m13',
 'ehc3p3m14',
 'ehc3p3m15',
 'ehc3p3m16',
 'ehc3p3m17',
 'ehc3p3m18',
 'ehc3p3',
 'ehc4p3m1',
 'ehc4p3m2',
 'ehc4p3m3',
 'ehc4p3m4',
 'ehc4p3m5',
 'ehc4p3m6',
 'ehc4p3m7',
 'ehc4p3m8',
 'ehc4p3m9',
 'ehc4p3m10',
 'ehc4p3m11',
 'ehc4p3m12',
 'ehc4p3m13',
 'ehc4p3m14',
 'ehc4p3m15',
 'ehc4p3m16',
 'ehc4p3m17',
 'ehc4p3m18',
 'ehc4p3',
 'ehc5p3',
 'ehc6p3',
 'ehc6p3m',
 'ehc6p3y',
 'ehc1p4n',
 'ehc1p4g',
 'ehc2p4m1',
 'ehc2p4m2',
 'ehc2p4m3',
 'ehc2p4m4',
 'ehc2p4m5',
 'ehc2p4m6',
 'ehc2p4m7',
 'ehc2p4m8',
 'ehc2p4m9',
 'ehc2p4m10',
 'ehc2p4m11',
 'ehc2p4m12',
 'ehc2p4m13',
 'ehc2p4m14',
 'ehc2p4m15',
 'ehc2p4m16',
 'ehc2p4m17',
 'ehc2p4m18',
 'ehc2p4',
 'ehc3p4m1',
 'ehc3p4m2',
 'ehc3p4m3',
 'ehc3p4m4',
 'ehc3p4m5',
 'ehc3p4m6',
 'ehc3p4m7',
 'ehc3p4m8',
 'ehc3p4m9',
 'ehc3p4m10',
 'ehc3p4m11',
 'ehc3p4m12',
 'ehc3p4m13',
 'ehc3p4m14',
 'ehc3p4m15',
 'ehc3p4m16',
 'ehc3p4m17',
 'ehc3p4m18',
 'ehc3p4',
 'ehc4p4m1',
 'ehc4p4m2',
 'ehc4p4m3',
 'ehc4p4m4',
 'ehc4p4m5',
 'ehc4p4m6',
 'ehc4p4m7',
 'ehc4p4m8',
 'ehc4p4m9',
 'ehc4p4m10',
 'ehc4p4m11',
 'ehc4p4m12',
 'ehc4p4m13',
 'ehc4p4m14',
 'ehc4p4m15',
 'ehc4p4m16',
 'ehc4p4m17',
 'ehc4p4m18',
 'ehc4p4',
 'ehc5p4',
 'ehc6p4',
 'ehc6p4m',
 'ehc6p4y',
 'ehc1p5n',
 'ehc1p5g',
 'ehc2p5m1',
 'ehc2p5m2',
 'ehc2p5m3',
 'ehc2p5m4',
 'ehc2p5m5',
 'ehc2p5m6',
 'ehc2p5m7',
 'ehc2p5m8',
 'ehc2p5m9',
 'ehc2p5m10',
 'ehc2p5m11',
 'ehc2p5m12',
 'ehc2p5m13',
 'ehc2p5m14',
 'ehc2p5m15',
 'ehc2p5m16',
 'ehc2p5m17',
 'ehc2p5m18',
 'ehc2p5',
 'ehc3p5m1',
 'ehc3p5m2',
 'ehc3p5m3',
 'ehc3p5m4',
 'ehc3p5m5',
 'ehc3p5m6',
 'ehc3p5m7',
 'ehc3p5m8',
 'ehc3p5m9',
 'ehc3p5m10',
 'ehc3p5m11',
 'ehc3p5m12',
 'ehc3p5m13',
 'ehc3p5m14',
 'ehc3p5m15',
 'ehc3p5m16',
 'ehc3p5m17',
 'ehc3p5m18',
 'ehc3p5',
 'ehc4p5m1',
 'ehc4p5m2',
 'ehc4p5m3',
 'ehc4p5m4',
 'ehc4p5m5',
 'ehc4p5m6',
 'ehc4p5m7',
 'ehc4p5m8',
 'ehc4p5m9',
 'ehc4p5m10',
 'ehc4p5m11',
 'ehc4p5m12',
 'ehc4p5m13',
 'ehc4p5m14',
 'ehc4p5m15',
 'ehc4p5m16',
 'ehc4p5m17',
 'ehc4p5m18',
 'ehc4p5',
 'ehc5p5',
 'ehc6p5',
 'ehc6p5m',
 'ehc6p5y',
 'ehc20d',
 'ehc20m',
 'ehc20y',
 'ehc7k1n',
 'ehc7k2n',
 'ehc7k3n',
 'ehc7k4n',
 'ehc7k5n',
 'ehc7k6n',
 'ehc7k7n',
 'ehc7k8n',
 'ehc7k9n',
 'ehc7k10n',
 'ehc7k1g',
 'ehc7k2g',
 'ehc7k3g',
 'ehc7k4g',
 'ehc7k5g',
 'ehc7k6g',
 'ehc7k7g',
 'ehc7k8g',
 'ehc7k9g',
 'ehc7k10g',
 ...]

In [23]:
# Standard information about anchor.
anchor_rel = pf_1[["id", "pid", "wave", "cohort", "sex_gen", "age", "homosex_new", "relstat", "marstat", "np", "ncoh", "nmar", "meetdur", "reldur", "cohabdur", "mardur", "nkids", "yeduc"]]

In [24]:
anchor_rel

,id,pid,wave,cohort,sex_gen,age,homosex_new,relstat,marstat,np,ncoh,nmar,meetdur,reldur,cohabdur,mardur,nkids,yeduc
0,111000.0,NaN,1 2008/09,3 1971-1973,2 Female,37.0,NaN,6 Divorced/separated single,3 Divorced/dissolved civil union,4.0,1.0,1.0,NaN,NaN,NaN,NaN,3.0,11.5
1,174000.0,NaN,1 2008/09,2 1981-1983,1 Male,25.0,1 Gay,1 Never married single,1 Never married,2.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,13.0
2,309000.0,309101.0,1 2008/09,2 1981-1983,2 Female,27.0,0 Hetero,4 Married COHAB,2 Married/civil union,1.0,0.0,0.0,68.0,61.0,57.0,47.0,1.0,12.0
3,423000.0,NaN,1 2008/09,1 1991-1993,1 Male,16.0,NaN,1 Never married single,1 Never married,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0 currently enrolled
4,828000.0,NaN,1 2008/09,1 1991-1993,1 Male,16.0,NaN,1 Never married single,1 Never married,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0 currently enrolled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12397,749548000.0,NaN,1 2008/09,1 1991-1993,2 Female,17.0,NaN,1 Never married single,1 Never married,4.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,10.0
12398,749656000.0,NaN,1 2008/09,1 1991-1993,1 Male,15.0,NaN,1 Never married single,1 Never married,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0 currently enrolled
12399,749700000.0,NaN,1 2008/09,1 1991-1993,2 Female,16.0,NaN,1 Never married single,1 Never married,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0 currently enrolled
12400,749725000.0,749725101.0,1 2008/09,2 1981-1983,1 Male,27.0,0 Hetero,4 Married COHAB,2 Married/civil union,1.0,0.0,0.0,64.0,63.0,50.0,33.0,0.0,12.0
12401,749731000.0,NaN,1 2008/09,1 1991-1993,2 Female,16.0,NaN,1 Never married single,1 Never married,1.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,9.0